repos:
  - repo: https://github.com/hhatto/autopep8.git
    rev: v2.3.1
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(cdk)/tests/unit/snapshots
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4', '--no-ensure-ascii']
        exclude: ^(cdk)/tests/unit/snapshots
      - id: check-yaml
