version: "3.8"

services:

  postgres:
    build:
      context: ./docker/postgres/
    image: igvfd-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"

  pyramid:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: igvfd-pyramid
    volumes:
      - ".:/igvfd"
      - "/igvfd/src/igvfd.egg-info"
    command: pytest --cov=igvfd -s -o junit_family=legacy --junitxml=./.test-results/junit.xml
    ports:
      - "6543:6543"
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: igvfd-nginx
    volumes:
      - "./config/nginx/docker.conf:/etc/nginx/nginx.conf"
    command: nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /dev/null;'
    ports:
      - "8000:8000"
    depends_on:
      - pyramid
