version: "3.8"

services:

  localstack:
    build:
      context: ./docker/localstack/
    image: igvfd-localstack
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - SERVICES=sqs
      - LS_LOG=warn
    ports:
      - "4566:4566"
    volumes:
      - "./docker/localstack/create_localstack.sh:/docker-entrypoint-initaws.d/create_localstack.sh"

  postgres:
    build:
      context: ./docker/postgres/
    image: igvfd-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"

  pyramid:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: igvfd-pyramid
    environment:
      - LOCALSTACK_ENDPOINT_URL=http://localstack:4566
      - TRANSACTION_QUEUE_URL=http://localstack:4566/000000000000/transaction-queue
    volumes:
      - ".:/igvfd"
      - "/igvfd/src/igvfd.egg-info"
    command: pytest --cov=igvfd -s -o junit_family=legacy --junitxml=./.test-results/junit.xml -m 'not indexing'
    ports:
      - "6543:6543"
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: igvfd-nginx
    volumes:
      - "./config/nginx/docker.conf:/etc/nginx/nginx.conf"
    command: nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /dev/null;'
    ports:
      - "8000:8000"
    depends_on:
      - pyramid
